package pojo;

import typehandler.EnableCard;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customer
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbggenerated
     */
    private Long id;
    
    public Customer(){
    	super();
    }

    public Customer(Long id, String userName, String password, String country, String tel, EnableCard enablecard) {
		super();
		this.id = id;
		this.userName = userName;
		this.password = password;
		this.country = country;
		this.tel = tel;
		this.enablecard = enablecard;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.enablecard
     *
     * @mbggenerated
     */
    private EnableCard enablecard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.user_name
     *
     * @return the value of customer.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.user_name
     *
     * @param userName the value for customer.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.password
     *
     * @return the value of customer.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.password
     *
     * @param password the value for customer.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.country
     *
     * @return the value of customer.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.country
     *
     * @param country the value for customer.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.tel
     *
     * @return the value of customer.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.tel
     *
     * @param tel the value for customer.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.enablecard
     *
     * @return the value of customer.enablecard
     *
     * @mbggenerated
     */
    public EnableCard getEnablecard() {
        return enablecard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.enablecard
     *
     * @param enablecard the value for customer.enablecard
     *
     * @mbggenerated
     */
    public void setEnablecard(EnableCard enablecard) {
        this.enablecard = enablecard;
    }

	@Override
	public String toString() {
		return "Customer [id=" + id + ", userName=" + userName + ", password=" + password + ", country=" + country
				+ ", tel=" + tel + ", enablecard=" + enablecard + "]";
	}
    
}