package pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_card
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class UserCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card.card_id
     *
     * @mbggenerated
     */
    private Long cardId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card.customer_id
     *
     * @return the value of user_card.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card.customer_id
     *
     * @param customerId the value for user_card.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card.card_id
     *
     * @return the value of user_card.card_id
     *
     * @mbggenerated
     */
    public Long getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card.card_id
     *
     * @param cardId the value for user_card.card_id
     *
     * @mbggenerated
     */
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }
}