package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.CardTrade;
import pojo.CardTradeExample;

public interface CardTradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_trade
     *
     * @mbggenerated
     */
    int countByExample(CardTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_trade
     *
     * @mbggenerated
     */
    int deleteByExample(CardTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_trade
     *
     * @mbggenerated
     */
    int insert(CardTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_trade
     *
     * @mbggenerated
     */
    int insertSelective(CardTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_trade
     *
     * @mbggenerated
     */
    List<CardTrade> selectByExample(CardTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_trade
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CardTrade record, @Param("example") CardTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_trade
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CardTrade record, @Param("example") CardTradeExample example);
}