package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.Tradeinfo;
import pojo.TradeinfoExample;

public interface TradeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeinfo
     *
     * @mbggenerated
     */
    int countByExample(TradeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeinfo
     *
     * @mbggenerated
     */
    int deleteByExample(TradeinfoExample example);

    List<Tradeinfo> selectAllTradeInfoById(Long cardid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeinfo
     *
     * @mbggenerated
     */
    int insert(Tradeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeinfo
     *
     * @mbggenerated
     */
    int insertSelective(Tradeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeinfo
     *
     * @mbggenerated
     */
    List<Tradeinfo> selectByExample(TradeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeinfo
     *
     * @mbggenerated
     */
    Tradeinfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tradeinfo record, @Param("example") TradeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tradeinfo record, @Param("example") TradeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tradeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tradeinfo record);
}