package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.UserCard;
import pojo.UserCardExample;

public interface UserCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated
     */
    int countByExample(UserCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated
     */
    int deleteByExample(UserCardExample example);
    
    Long selectCardidByCustomerid(Long customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated
     */
    int insert(UserCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated
     */
    int insertSelective(UserCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated
     */
    List<UserCard> selectByExample(UserCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserCard record, @Param("example") UserCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserCard record, @Param("example") UserCardExample example);
}